baseURL = "/"
languageCode = "en-us"
title = "Roti Kapda Makaan"
theme = "kube"
description = "It's a JS package which creates unique combinations of hinglish words. Next time you want to share a unique id, you might as well share 42-roti-kapda-makaan!"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Rahul Ramteke" # add your company name
  github = "https://github.com/iostreamer-X" # add your github profile name
  email = "iostreamer007@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "/faq/"
[[menu.main]]
    name = "Download"
    weight = -100
    url = "/download/"
